import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { cookies } from 'next/headers';
import { jwtVerify } from 'jose';
import { getJwtSecretKey } from '@/lib/auth';

async function getUserFromCookie() {
  const cookieStore = await cookies();
  const token = cookieStore.get('auth_token')?.value;
  if (!token) return null;
  try {
    const { payload } = await jwtVerify(token, getJwtSecretKey());
    return payload as { userId: string; email: string; role: string };
  } catch {
    return null;
  }
}

export async function GET() {
  try {
    const session = await getUserFromCookie();
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // 1. Fetch user detail
    let user = await prisma.user.findUnique({
      where: { id: session.userId }
    });

    if (!user) {
      return NextResponse.json({ error: 'User not found' }, { status: 404 });
    }

    if (!user.isAffiliate && user.role !== 'admin') {
      return NextResponse.json({ error: 'คุณยังไม่ได้รับการเปิดใช้งานระบบแนะนำเพื่อน (Affiliate) กรุณาติดต่อผู้ดูแลระบบ' }, { status: 403 });
    }

    // 2. Generate referral code if missing (for legacy users)
    if (!user.referralCode) {
      const referralCode = `REF-${Math.random().toString(36).substring(2, 8).toUpperCase()}`;
      user = await prisma.user.update({
        where: { id: user.id },
        data: { referralCode }
      });
    }

    // 3. Count total signups referred by this user
    const referees = await prisma.user.findMany({
      where: { referredById: user.id },
      select: {
        id: true,
        email: true,
        subscriptionStatus: true,
        subscriptionPlan: true,
        createdAt: true
      }
    });

    const totalSignups = referees.length;

    // 4. Count active/renewed users (currently monthly and active)
    const activeReferees = referees.filter(
      r => r.subscriptionStatus === 'active' && r.subscriptionPlan === 'monthly'
    ).length;

    // 5. Fetch all commissions generated by this referrer
    const commissions = await prisma.affiliateCommission.findMany({
      where: { referrerId: user.id },
      include: {
        referred: {
          select: { email: true }
        },
        payment: {
          select: { amount: true, createdAt: true }
        }
      },
      orderBy: { createdAt: 'desc' }
    });

    // 6. Calculate summaries
    let pendingCommission = 0; // expected to receive this month
    let paidCommission = 0; // historically paid out
    let totalRevenueGenerated = 0; // sum of all referred payments

    commissions.forEach(c => {
      if (c.status === 'pending') {
        pendingCommission += c.amount;
      } else if (c.status === 'paid') {
        paidCommission += c.amount;
      }
      totalRevenueGenerated += c.payment.amount;
    });

    return NextResponse.json({
      success: true,
      referralCode: user.referralCode,
      referralLink: `https://goldaisig.com/?ref=${user.referralCode}`,
      affiliateRate: user.affiliateRate,
      metrics: {
        totalSignups,
        activeReferees,
        totalRevenueGenerated,
        pendingCommission,
        paidCommission
      },
      referrals: referees.map(r => ({
        email: r.email.replace(/(.{2})(.*)(@.*)/, "$1***$3"), // mask email for privacy
        status: r.subscriptionStatus,
        plan: r.subscriptionPlan,
        createdAt: r.createdAt
      })),
      commissions: commissions.map(c => ({
        id: c.id,
        referredEmail: c.referred.email.replace(/(.{2})(.*)(@.*)/, "$1***$3"),
        paymentAmount: c.payment.amount,
        commissionAmount: c.amount,
        status: c.status,
        createdAt: c.createdAt
      }))
    });

  } catch (err: any) {
    console.error('Affiliate stats API error:', err);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
